---
title: "Homework 5"
author: "Xiao(Freeman)_Zhang"
date: "2022-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls()) # Clear the workspace
```

```{r}
data.rating <- read.csv("~/Desktop/UW - Madison/Fall 2022/GB 740/Week 9/Homework 5/RatingData.csv")
summary(data.rating)
head(data.rating)

```

```{r}
library(dplyr)
summary <- data.rating %>%
  mutate(treat = as.factor(treat)) %>% 
  mutate(month = as.factor(month)) %>%
  group_by(treat,month) %>%  #group the data by treatregion and month
  summarise (n = length(id), 
             m.rating = mean(rating),
             error = sd(rating)/sqrt(n),
             lci = m.rating - 1.96*error,
             uci = m.rating + 1.96*error)
summary
```

```{r}
library(ggplot2)
summary %>%
  ggplot(aes(x=month, y = m.rating, group = treat, color = treat)) +
  # here we declare what's the horizontal and vertical vars for the plot
  # and what variable we want to group by
  geom_point()+ #add the dots to the plot
  geom_line()+ # connect the dots
  geom_vline(xintercept=12.5, linetype="dashed", color = "blue")+
  # add a dash line to indicate the change time.
  geom_errorbar(aes(ymin = lci, ymax = uci, 
                    color=treat), width= 0.3)+
  scale_y_continuous(limits = c(3.5,5)) + #define the range of y-axis
  ylab("Average Rating") + 
  xlab("Month") + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"), 
        axis.text.x= element_text(size = 10), legend.position = c(0.2,0.9),
        plot.title=element_text(hjust=.5) ) +
  scale_color_discrete(name=NULL, labels = c("Singal-dimensional Rating", "Regionmulti-dimensional rating"))

```

```{r}
#generate a dummy variable named post to indicate 
#if this observation is recorded after the change month or not
data.rating$post = ifelse(data.rating$month>12,1,0) 

#generate a dummy variable named post to indicate 
#if this observation is in the treatment region AND recorded after the change month
#Notice that since the variable treatregion is also a 0/1 indicator, multiplying
#these two variables also gives you a 0/1 indicator. 
data.rating$post_treat = data.rating$post*data.rating$treat
head(data.rating)
```

```{r}
library(fixest)  # use for regression approach + cluster-robust robust standard errors


fit.rating = feols(rating~treat+post+post_treat, data = data.rating)

# second argument adjusts standard errors because of clustering problem 
summary(fit.rating, cluster~id)
```